#!/bin/bash

#SBATCH -c 6 		# number of cores requested -- this needs to be greater than or equal to the number of cores you plan to use to run your job
#SBATCH --exclusive
#SBATCH --job-name STAR_index_generator 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
#SBATCH --mail-type=ALL
#SBATCH --mail-user=spascoe@mit.edu


module load star/2.7.9a

STAR --runThreadN 6 \
--runMode genomeGenerate \
--genomeDir reference_genome/hg38_index \
--genomeFastaFiles reference_genome/ncbi_dataset/ncbi_dataset/data/GCF_000001405.40/GCF_000001405.40_GRCh38.p14_genomic.fna \
--sjdbGTFfile reference_genome/ncbi_dataset/ncbi_dataset/data/GCF_000001405.40/genomic.gtf \
